//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TEST.MonitorWCF {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MonitorWCF.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/log", ReplyAction="http://tempuri.org/IService1/logResponse")]
        void log(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/log", ReplyAction="http://tempuri.org/IService1/logResponse")]
        System.Threading.Tasks.Task logAsync(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getLogs", ReplyAction="http://tempuri.org/IService1/getLogsResponse")]
        string[] getLogs();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getLogs", ReplyAction="http://tempuri.org/IService1/getLogsResponse")]
        System.Threading.Tasks.Task<string[]> getLogsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : TEST.MonitorWCF.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<TEST.MonitorWCF.IService1>, TEST.MonitorWCF.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void log(string value) {
            base.Channel.log(value);
        }
        
        public System.Threading.Tasks.Task logAsync(string value) {
            return base.Channel.logAsync(value);
        }
        
        public string[] getLogs() {
            return base.Channel.getLogs();
        }
        
        public System.Threading.Tasks.Task<string[]> getLogsAsync() {
            return base.Channel.getLogsAsync();
        }
    }
}
