#!/usr/bin/python3
# -*- coding: utf-8 -*

import cgi
import os
import urllib.parse as urlparse 

form = cgi.FieldStorage()
print("Content-type: text/html; charset=utf-8\n")

query_string=os.environ['QUERY_STRING']

url = "http://localhost:8080/index.py?"+query_string

parsed = urlparse.urlparse(url)
nom = urlparse.parse_qs(parsed.query)['nom'][0]
prenom = urlparse.parse_qs(parsed.query)['prenom'][0]

html2 = """<!DOCTYPE html>
<HTML>
	<HEAD>
		<TITLE>Doc. Produit par un CGI</TITLE>
	</HEAD>
	<BODY>
		<H1>Bonjour """+nom+" "+prenom+"""<H1>
	</BODY>
</HTML>"""

print(html2)